### ISSUE TITLE
Code optimisation

### ISSUE THREAD

**Issue by flumexx** [NilEis/JavaScript-Raytracer#3]
Hey,

habe grade mir deinen Code mal angesehen. Habe ein wenig was optimiert. Ich konnte leider keinen Request stellen, deshalb hier:

**Main.js**

/**
 * @event onmousemove
 *
 * @function updateMouse
 * EventListener on body
 */
document.getElementById("main").addEventListener("mousemove", function () {
    updateMouse(event);
});`

**index.html**
Remove: `<body onmousemove="updateMouse(event)">`
Add: `<body id="main">`

**Comment by flumexx** [comment]
Der Code will nicht so ganz formatiert werden, sorry dafür.

**Comment by NilEis** [comment]
Danke, habs geändert.
